/**
 * Writes seed.sql: the synthetic starting electorate.
 *
 *   npm run seed
 *   npx wrangler d1 execute ols-votes --local  --file=./seed.sql
 *   npx wrangler d1 execute ols-votes --remote --file=./seed.sql
 *
 * Why seed at all: the first real visitor would otherwise land on a results
 * screen containing their own single vote, which teaches nothing. ~800 simulated
 * voters per theme make the seat allocation legible immediately, and the results
 * screen says plainly how many voters are simulated.
 *
 * Rows are individual votes rather than pre-aggregated counts, so the tally query
 * is identical for seed and real votes and `is_seed` is the only difference.
 *
 * Idempotent: deletes existing seed rows for each theme before inserting, so
 * re-running does not stack electorates on top of each other. Real votes
 * (is_seed = 0) are never touched.
 */

import { writeFileSync } from 'node:fs'
import { getThemes } from '../src/data/index.js'
import { REGIONS } from '../src/data/regions.js'
import { mockTallies } from '../src/lib/mockElectorate.js'

const VOTES_PER_THEME = 800
const BATCH = 200 // keep each INSERT statement well inside D1's limits

// Every theme across every region, deduplicated — regions share the universal ones.
const themes = new Map()
for (const regionId of Object.keys(REGIONS)) {
  for (const theme of getThemes(regionId)) themes.set(theme.id, theme)
}

const lines = [
  '-- Generated by scripts/generate-seed.mjs. Do not edit by hand.',
  `-- ${VOTES_PER_THEME} synthetic votes per theme, ${themes.size} themes.`,
  '',
]

let total = 0

for (const theme of themes.values()) {
  const tallies = mockTallies(theme, VOTES_PER_THEME)

  // One row per vote, so COUNT(*) works the same for seed and real ballots.
  const rows = []
  for (const { listId, candidateId, votes } of tallies) {
    for (let i = 0; i < votes; i += 1) {
      rows.push({ listId, candidateId, i })
    }
  }

  lines.push(`-- ${theme.name}: ${rows.length} votes`)
  lines.push(`DELETE FROM votes WHERE theme_id = '${theme.id}' AND is_seed = 1;`)

  for (let start = 0; start < rows.length; start += BATCH) {
    const chunk = rows.slice(start, start + BATCH)
    const values = chunk
      .map(
        (row, offset) =>
          `('seed:${theme.id}:${row.listId}:${row.candidateId}:${start + offset}',` +
          `'${theme.id}','${row.listId}','${row.candidateId}',1)`,
      )
      .join(',\n  ')
    lines.push(
      `INSERT OR IGNORE INTO votes (token, theme_id, list_id, candidate_id, is_seed) VALUES\n  ${values};`,
    )
  }

  lines.push('')
  total += rows.length
}

writeFileSync(new URL('../seed.sql', import.meta.url), `${lines.join('\n')}\n`)
console.log(`seed.sql written: ${total} votes across ${themes.size} themes`)
